name = "QDUtilLib"
version = "2.3.1"
license = "MIT"
author = "David Lauvergnat"
maintainer = "david.lauvergnat@universite-paris-saclay.fr"
copyright = "2023 David Lauvergnat"

[library]
source-dir="SRC"
type = "static"

[[test]]
name="TestQDLib"
source-dir="TESTS"
main="Test_QDLib.f90"


[[executable]]
name="AppQDLib"
source-dir="APP"
main="App_QDLib.f90"

[install]
library = true

[build]
link = ["blas", "lapack"]


[preprocess]
cpp.macros = ["__LAPACK=1","__RKIND=real64","__WITHRK16=1"]

[fortran]
implicit-external = true


[extra.ford]
project = "QDUtilLib"
exclude_dir= "../doc"
# TOML allows comments, which is handy
summary = """
List of Fortran modules which contain utilities for codes.
All modules contain a testing unit.
"""
extensions = ['f90']
graph = false
preprocess = false
search = false
display = ['public','protected']
#preprocessor = ["gfortran -E"]
#fpp_extensions = ['f90']
#display = ["public", "protected"]
#max_frontpage_items = 4
#{!README.md!}
